export const EXAMPLE = 'EXAMPLE'

export const BG_LOAD_START = 'BG_LOAD_START'
export const BG_LOAD_SUCCESS = 'BG_LOAD_SUCCESS'
export const BG_LOAD_FAILURE = 'BG_LOAD_FAILURE'
export const NEXT_SLIDE = 'NEXT_SLIDE'
export const PREV_SLIDE = 'PREV_SLIDE'

export const GEOLOCATION_START = 'GEOLOCATION_START'
export const GEOLOCATION_SUCCESS = 'GEOLOCATION_SUCCESS'
export const GEOLOCATION_FAILURE = 'GEOLOCATION_FAILURE'

export const GET_LOCATION_START = 'GET_LOCATION_START'
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS'
export const GET_LOCATION_FAILURE = 'GET_LOCATION_FAILURE'

export const SET_CITY = 'SET_CITY'

export const SEARCH_KEYWORD = 'SEARCH_KEYWORD'

export const AUTO_START = 'AUTO_START'
export const AUTO_SUCCESS = 'AUTO_SUCCESS'
export const AUTO_FAILURE = 'AUTO_FAILURE'

export const LAT_LONG_START = 'LAT_LONG_START'
export const LAT_LONG_SUCCESS = 'LAT_LONG_SUCCESS'
export const LAT_LONG_FAILURE = 'LAT_LONG_FAILURE'

export const SEARCH_START = 'SEARCH_START'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'