export const EXAMPLE = 'EXAMPLE'

export const TOGGLE_CONTACT_MODAL = 'TOGGLE_CONTACT_MODAL';

export const LOADING_HERO_PICTURES = 'LOADING_HERO_PICTURES';
export const LOADED_HERO_PICTURES = 'LOADED_HERO_PICTURES';