export const EXAMPLE = 'EXAMPLE'

export const BG_LOAD_START = 'BG_LOAD_START'
export const BG_LOAD_SUCCESS = 'BG_LOAD_SUCCESS'
export const BG_LOAD_FAILURE = 'BG_LOAD_FAILURE'
export const NEXT_SLIDE = 'NEXT_SLIDE'
export const PREV_SLIDE = 'PREV_SLIDE'

export const GEOLOCATION_START = 'GEOLOCATION_START'
export const GEOLOCATION_SUCCESS = 'GEOLOCATION_SUCCESS'
export const GEOLOCATION_FAILURE = 'GEOLOCATION_FAILURE'

export const GET_LOCATION_START = 'GET_LOCATION_START'
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS'
export const GET_LOCATION_FAILURE = 'GET_LOCATION_FAILURE'